import jsPDF from 'jspdf';
import type { LoadResult } from '../engines/loadCalculator';
import type { PanelSizingResult } from '../engines/panelSizing';
import type { BatterySizingResult } from '../engines/batterySizing';
import type { InverterSizingResult } from '../engines/inverterSizing';
import type { WireSizingResult } from '../engines/wireSizing';
import type { RoiResult } from '../engines/roiCalculator';
import type { ProjectConfig } from '../store/solarStore';
import irradianceData from '../data/irradiance.json';

const SUN='#F5A623',DARK='#0d0f12',BG2='#13171d',BG3='#161a23';
const TEXT='#e8ecf4',TEXT2='#8a96b0',TEXT3='#4a5470';
const GREEN='#22c55e',BORDER='#2a3040';
function rgb(h:string):[number,number,number]{return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];}

export function exportToPDF(project:ProjectConfig,load:LoadResult,panels:PanelSizingResult,batteries:BatterySizingResult,inverter:InverterSizingResult,wiring:WireSizingResult,roi:RoiResult,locationName:string,chemistryName:string){
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'});
  const pw=210,lm=15,rm=15,cw=pw-lm-rm;
  let y=0;
  const sf=(h:string)=>doc.setFillColor(...rgb(h));
  const ss=(h:string)=>doc.setDrawColor(...rgb(h));
  const st=(h:string)=>doc.setTextColor(...rgb(h));
  const B=(s:number)=>{doc.setFont('helvetica','bold');doc.setFontSize(s);};
  const N=(s:number)=>{doc.setFont('helvetica','normal');doc.setFontSize(s);};
  function np(){doc.addPage();sf(DARK);doc.rect(0,0,pw,12,'F');st(SUN);B(10);doc.text('SolarX',lm,8);st(TEXT3);N(7);doc.text(project.name,lm+18,8);doc.text(`${project.systemType.toUpperCase()} · ${project.systemVoltage}V`,pw-rm,8,{align:'right'});y=18;}
  function cp(n:number){if(y+n>275)np();}
  function sh(title:string,sub?:string){cp(16);sf(BG2);doc.rect(lm,y,cw,10,'F');ss(SUN);doc.setLineWidth(0.4);doc.line(lm,y,lm,y+10);st(SUN);B(9);doc.text(title,lm+5,y+6.5);if(sub){st(TEXT3);N(7);doc.text(sub,lm+5+doc.getTextWidth(title)+4,y+6.5);}y+=14;}
  function r2(k:string,v:string,hi=false){cp(8);st(TEXT2);N(8);doc.text(k,lm+3,y+4);st(hi?SUN:TEXT);if(hi)B(8);else N(8);doc.text(v,lm+cw-3,y+4,{align:'right'});ss(BORDER);doc.setLineWidth(0.1);doc.line(lm,y+7,lm+cw,y+7);y+=8;}
  function sb(x:number,bw:number,label:string,value:string,unit:string,color=TEXT){sf(BG2);ss(BORDER);doc.setLineWidth(0.2);doc.roundedRect(x,y,bw,18,1.5,1.5,'FD');st(TEXT3);N(6);doc.text(label.toUpperCase(),x+4,y+6);st(color);B(11);doc.text(value,x+4,y+13);st(TEXT2);N(7);doc.text(unit,x+4+doc.getTextWidth(value)+1.5,y+13);}

  // COVER
  sf(DARK);doc.rect(0,0,pw,297,'F');
  const cx=pw/2,cy=65,sr=18;
  sf(SUN);doc.circle(cx,cy,sr,'F');
  ss(SUN);doc.setLineWidth(2.5);
  [[0,1],[0,-1],[1,0],[-1,0],[0.707,0.707],[-0.707,0.707],[0.707,-0.707],[-0.707,-0.707]].forEach(([dx,dy])=>{doc.line(cx+dx*(sr+3),cy+dy*(sr+3),cx+dx*(sr+9),cy+dy*(sr+9));});
  st(TEXT);B(28);doc.text('SolarX',pw/2,95,{align:'center'});
  st(SUN);N(11);doc.text('Solar Electrical Install Companion',pw/2,103,{align:'center'});
  ss(BORDER);doc.setLineWidth(0.3);doc.line(lm+20,110,pw-lm-20,110);
  sf(BG2);doc.roundedRect(lm+10,116,cw-20,52,2,2,'F');
  st(SUN);B(13);doc.text(project.name,pw/2,128,{align:'center'});
  [['System Type',project.systemType.charAt(0).toUpperCase()+project.systemType.slice(1)],['System Voltage',`${project.systemVoltage}V DC`],['Location',locationName],['Date',new Date().toLocaleDateString('en-PH',{year:'numeric',month:'long',day:'numeric'})]].forEach(([k,v],i)=>{const iy=137+i*9;st(TEXT2);N(8);doc.text(k,lm+18,iy);st(TEXT);B(8);doc.text(v,pw-lm-18,iy,{align:'right'});if(i<3){ss(BORDER);doc.setLineWidth(0.1);doc.line(lm+14,iy+3,pw-lm-14,iy+3);}});
  const metrics=[{label:'Daily Load',val:load.dailyKwh.toFixed(2),unit:'kWh/day'},{label:'Solar Array',val:String(panels.numberOfPanels),unit:'panels'},{label:'Battery Bank',val:String(batteries.numberOfBatteries),unit:'units'},{label:'Inverter',val:inverter.inverter.recommendedInverterKva.toFixed(1),unit:'kVA'}];
  const mbw=(cw-20)/4-3;
  st(TEXT3);N(7);doc.text('KEY RESULTS',pw/2,180,{align:'center'});
  metrics.forEach((m,i)=>{const bx=lm+10+i*(mbw+4);sf('#1a1f28');ss(SUN);doc.setLineWidth(0.3);doc.roundedRect(bx,184,mbw,22,1.5,1.5,'FD');st(TEXT3);N(6);doc.text(m.label.toUpperCase(),bx+mbw/2,191,{align:'center'});st(SUN);B(12);doc.text(m.val,bx+mbw/2,198,{align:'center'});st(TEXT2);N(6.5);doc.text(m.unit,bx+mbw/2,203,{align:'center'});});
  const pbY=roi.yearlyProjection.find(yy=>yy.netPosition>=0)?.year;
  sf('#1a1f28');ss(GREEN);doc.setLineWidth(0.5);doc.roundedRect(lm+30,214,cw-60,16,2,2,'FD');
  st(TEXT2);N(8);doc.text('Estimated Payback Period:',lm+34,224);
  st(GREEN);B(10);doc.text(pbY?`${pbY} Years`:`${roi.paybackYears.toFixed(1)} Years`,pw-lm-34,224,{align:'right'});
  st(TEXT3);N(7);doc.text('Generated by SolarX · Solar Electrical Install Companion',pw/2,280,{align:'center'});
  doc.text('For planning purposes only. Consult a licensed electrical engineer before installation.',pw/2,286,{align:'center'});

  // PAGE 2 — LOAD
  np();sh('Load Profile',`${load.items.length} appliances`);
  sb(lm,cw/4-2,'Daily Energy',load.dailyKwh.toFixed(2),'kWh',SUN);
  sb(lm+cw/4+1,cw/4-2,'Total Load',load.totalWatts.toFixed(0),'W');
  sb(lm+cw/2+1,cw/4-2,'Peak Load',load.peakLoad.toFixed(0),'W');
  sb(lm+3*cw/4+2,cw/4-2,'Surge Load',load.surgeLoad.toFixed(0),'W');
  y+=24;
  sf(BG2);doc.rect(lm,y,cw,8,'F');B(7);st(TEXT3);
  ['Appliance','Watts','Qty','Hrs/Day','kWh/Day'].forEach((h,i)=>{const xs=[lm+3,lm+75,lm+105,lm+130,lm+cw-3];doc.text(h,xs[i],y+5.5,{align:i===4?'right':'left'});});y+=10;
  load.items.forEach((item,idx)=>{cp(8);if(idx%2===0){sf(BG3);doc.rect(lm,y,cw,7.5,'F');}st(TEXT);N(7.5);doc.text(item.name,lm+3,y+5);st(TEXT2);doc.text(`${item.watts}W`,lm+75,y+5);doc.text(String(item.quantity),lm+105,y+5);doc.text(`${item.hoursPerDay}h`,lm+130,y+5);st(SUN);B(7.5);doc.text(((item.watts*item.quantity*item.hoursPerDay)/1000).toFixed(3),lm+cw-3,y+5,{align:'right'});y+=7.5;});
  cp(10);sf(BG2);doc.rect(lm,y,cw,9,'F');ss(SUN);doc.setLineWidth(0.3);doc.line(lm,y,lm+cw,y);st(TEXT);B(8);doc.text('TOTAL',lm+3,y+6);st(SUN);doc.text(`${load.dailyKwh.toFixed(2)} kWh/day`,lm+cw-3,y+6,{align:'right'});y+=14;

  // PAGE 3 — SYSTEM
  np();sh('Solar Panel Sizing');
  [['Required capacity',`${panels.requiredKwp.toFixed(2)} kWp`,true],['Panel wattage',`${project.panelWattage} W`],['Number of panels',String(panels.numberOfPanels),true],['Configuration',`${panels.panelsInSeries}S × ${panels.stringsInParallel}P`],['Total array size',`${panels.totalKwp.toFixed(2)} kWp`],['Est. daily generation',`${panels.dailyGenerationKwh.toFixed(2)} kWh`],['Peak sun hours',`${irradianceData.find(l=>l.id===project.locationId)?.peakSunHours??'-'} hrs`]].forEach(([k,v,h])=>r2(k as string,v as string,!!h));y+=4;
  sh('Battery Bank Sizing');
  [['Chemistry',chemistryName],['Required capacity',`${batteries.requiredAh.toFixed(0)} Ah`,true],['Battery size',`${project.batteryAh} Ah @ ${project.systemVoltage}V`],['Configuration',`${batteries.batteriesInSeries}S × ${batteries.batteriesInParallel}P`],['Total batteries',String(batteries.numberOfBatteries),true],['Total capacity',`${batteries.totalCapacityKwh.toFixed(1)} kWh`],['Usable capacity',`${batteries.usableKwh.toFixed(1)} kWh`],['Autonomy',`${project.autonomyDays} day(s)`]].forEach(([k,v,h])=>r2(k as string,v as string,!!h));y+=4;
  sh('Inverter & Charge Controller');
  [['Inverter size',`${inverter.inverter.recommendedInverterKva.toFixed(1)} kVA`,true],['Type',inverter.inverter.inverterType],['MPPT rating',`${inverter.mppt.recommendedMpptAmps} A`],['Array Voc',`${inverter.mppt.openCircuitVoltageVoc} V`],['Array Isc',`${inverter.mppt.shortCircuitCurrentIsc.toFixed(1)} A`]].forEach(([k,v,h])=>r2(k as string,v as string,!!h));y+=4;

  // PAGE 4 — WIRING & ROI
  np();sh('Wire Sizing & Protection');
  sf(BG2);doc.rect(lm,y,cw,8,'F');B(7);st(TEXT3);
  ['Segment','Current','AWG','mm²','V-Drop','Fuse','Status'].forEach((h,i)=>{const xs=[lm+3,lm+52,lm+72,lm+88,lm+106,lm+124,lm+cw-3];doc.text(h,xs[i],y+5.5,{align:i===6?'right':'left'});});y+=10;
  wiring.segments.forEach((s,idx)=>{cp(8);if(idx%2===0){sf(BG3);doc.rect(lm,y,cw,7.5,'F');}st(TEXT);N(7.5);doc.text(s.segment.name,lm+3,y+5);st(TEXT2);doc.text(`${s.segment.currentAmps.toFixed(1)}A`,lm+52,y+5);st(SUN);doc.text(`#${s.recommendedAwg}`,lm+72,y+5);st(TEXT2);doc.text(`${s.recommendedMm2}`,lm+88,y+5);doc.text(`${s.voltageDropPercent.toFixed(2)}%`,lm+106,y+5);doc.text(`${s.fuseRating}A`,lm+124,y+5);st(s.withinSpec?GREEN:'#ef4444');B(7);doc.text(s.withinSpec?'OK':'OVER',lm+cw-3,y+5,{align:'right'});y+=7.5;});y+=8;
  sh('ROI & Financial Analysis');
  const rs=[{label:'Annual Savings',val:`₱${roi.annualSavingsPhp.toLocaleString('en-PH',{maximumFractionDigits:0})}`,color:GREEN},{label:'Payback Period',val:`${roi.paybackYears.toFixed(1)} yrs`,color:SUN},{label:'25-Year ROI',val:`${roi.roi25Years.toFixed(0)}%`,color:'#3b82f6'},{label:'CO₂ Saved/yr',val:`${(roi.co2SavedKgPerYear/1000).toFixed(1)} t`,color:'#14b8a6'}];
  const rbw=cw/4-3;
  rs.forEach((s,i)=>{const bx=lm+i*(rbw+4);sf(BG2);ss(BORDER);doc.setLineWidth(0.2);doc.roundedRect(bx,y,rbw,18,1.5,1.5,'FD');st(TEXT3);N(6);doc.text(s.label.toUpperCase(),bx+rbw/2,y+6,{align:'center'});st(s.color);B(9);doc.text(s.val,bx+rbw/2,y+13.5,{align:'center'});});y+=24;
  [['Total system cost',`₱${project.totalSystemCostPhp.toLocaleString('en-PH',{maximumFractionDigits:0})}`],['Annual savings',`₱${roi.annualSavingsPhp.toLocaleString('en-PH',{maximumFractionDigits:0})}`],['Payback period',`${roi.paybackYears.toFixed(1)} years`],['25-yr cumulative savings',`₱${roi.yearlyProjection[24]?.cumulativeSavings.toLocaleString('en-PH',{maximumFractionDigits:0})}`],['25-year ROI',`${roi.roi25Years.toFixed(1)}%`],['CO₂ saved per year',`${(roi.co2SavedKgPerYear/1000).toFixed(2)} metric tons`],['Equivalent trees planted',`${Math.round(roi.co2SavedKgPerYear/21)} trees`]].forEach(([k,v])=>r2(k,v));y+=6;

  // PAGE 5 — BOM
  np();sh('Bill of Materials');
  sf(BG2);doc.rect(lm,y,cw,8,'F');B(7);st(TEXT3);
  ['#','Component','Specification','Qty','Unit'].forEach((h,i)=>{const xs=[lm+3,lm+14,lm+65,lm+cw-22,lm+cw-3];doc.text(h,xs[i],y+5.5,{align:i>=3?'right':'left'});});y+=10;
  const bom=[['01','Solar Panel',`${project.panelWattage}W Monocrystalline PERC`,String(panels.numberOfPanels),'units'],['02','Battery',`${project.batteryAh}Ah ${project.systemVoltage}V ${project.batteryChemistryId.toUpperCase()}`,String(batteries.numberOfBatteries),'units'],['03','Inverter/Charger',`${inverter.inverter.recommendedInverterKva.toFixed(1)}kVA ${project.systemType}`,'1','unit'],['04','MPPT Controller',`${inverter.mppt.recommendedMpptAmps}A ${project.systemVoltage}V`,'1','unit'],['05','Panel Mount','Aluminum rail + L-bracket kit','1','set'],['06','MC4 Connectors','Male + Female pairs',String(panels.numberOfPanels*2),'pairs'],...wiring.segments.map((s,i)=>[`0${7+i}`,`DC Cable — ${s.segment.name}`,`AWG#${s.recommendedAwg} (${s.recommendedMm2}mm²)`,String(s.segment.lengthMeters),'meters']),['-','Circuit Breakers','DC + AC rated per segment','1','set'],['-','Grounding Kit','Earth rod + conductor','1','set'],['-','Surge Protectors (SPD)','DC + AC side','1','set']];
  bom.forEach((row,idx)=>{cp(8);if(idx%2===0){sf(BG3);doc.rect(lm,y,cw,7.5,'F');}st(TEXT3);N(7);doc.text(row[0],lm+3,y+5);st(TEXT);B(7.5);doc.text(row[1],lm+14,y+5);st(TEXT2);N(7);doc.text(row[2],lm+65,y+5);st(SUN);B(7.5);doc.text(row[3],lm+cw-22,y+5,{align:'right'});st(TEXT3);N(7);doc.text(row[4],lm+cw-3,y+5,{align:'right'});y+=7.5;});
  y+=10;sh('Installation Notes');
  [`• All DC wiring must be rated for outdoor/UV exposure (USE-2 or THWN-2).`,`• Install SPD (surge protection) on both DC and AC sides.`,`• Battery bank must be ventilated; keep away from heat sources.`,`• Verify minimum conductor sizes per NEC 690 or local PEC code.`,`• All metal frames, rails and enclosures must be properly earthed.`,`• Commission system with a licensed electrical engineer before energizing.`,`• This report is for planning only and does not replace engineering sign-off.`].forEach(note=>{cp(7);st(TEXT2);N(7.5);doc.text(note,lm+3,y);y+=6.5;});

  // PAGE NUMBERS
  const total=doc.getNumberOfPages();
  for(let p=1;p<=total;p++){doc.setPage(p);st(TEXT3);N(7);doc.text(`Page ${p} of ${total}`,pw-rm,290,{align:'right'});if(p>1)doc.text('SolarX Report — Confidential',lm,290);}

  doc.save(`SolarX_${project.name.replace(/\s+/g,'_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}
